apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: {{microservice1}}-mapping
spec:
  gatewayRef:
    name: {{appName}}-gateway
  routeConfigRef:
    name: {{microservice1}}-routes
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: {{microservice2}-mapping
spec:
  gatewayRef:
    name: {{appName}}-gateway
  routeConfigRef:
    name: {{microservice2}}-routes
