apiVersion: kontinue.io/v1alpha1
kind: OpinionTemplate
metadata:
  name: opinion-service-battery
spec:
  # default parameters. see ClusterSourceTemplate for more info. (optional)
  #
  params: []

  # jsonpath expression to instruct where in the object templated out an 
  # opinionated podTemplateSpec can be found (required)
  #
  opinionPath: .status.template

  # how to template out the kubernetes object. (required)
  #
  template:
    apiVersion: opinions.local/v1alpha1
    kind: WorkloadDecorator
    metadata:
      name: $(workload.name)$-workload-template
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/part-of: $(workload.name)$
          annotations:
            autoscaling.knative.dev/minScale: "1"
            autoscaling.knative.dev/maxScale: "1"
        spec:
          containers:
            - name: workload
              image: $(images[?(@.name=="solo-image-provider")].image)$
              env: $(workload.env)$
              resources: $(workload.resources)$
              securityContext:
                runAsUser: 1000
          imagePullSecrets:
            - name: registry-credentials