#
# WARNING: this yaml is for demonstration purposes only. Based on a work-in-progess product. Specs will change.
#
apiVersion: experimental.kontinue.io/v1
kind: Delivery
metadata:
  name: app-name-delivery
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:
    - name: app-name-delivery
      serviceAccountName: app-name-deployer
      fetch:
        - inline:
            paths:
              - path: workload1-routes
                type: copy
                sources: $(workload1.api-routes)$
              - path: workload2-routes
                type: copy
                sources: $(workload2.api-routes)$
              - path: api-mapping
                type: copy
                sources: ../../apigrid/mapping.yaml
              - path: gateway-config
                type: copy
                sources: ../../apigrid/gateway.yaml
