#
# WARNING: this yaml is for demonstration purposes only. Based on a work-in-progess product. Specs will change.
#
apiVersion: experimental.kontinue.io/v1
kind: Delivery
metadata:
  name: app-name-delivery
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:
    - name: delivery
      templateRef:
        kind: DeliveryTemplate
        name: api-grid-delivery
