apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: workload1
  labels:
    # label to be matched against a `ClusterSupplyChain`s label selector.
    #
    app.tanzu.vmware.com/workload-type: web   # (1)

spec:
  # Source code location in a git repository. (optional)
  #
  git:
    url: git1
    ref: {branch: main}

  # image with the app already built (optional)
  #
  image: registry/app-name/workload1     # (2)

  # resource constraints for the main application. (optional)
  #
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m
---
apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: workload2
  labels:
    # label to be matched against a `ClusterSupplyChain`s label selector.
    #
    app.tanzu.vmware.com/workload-type: web   # (1)

spec:
  # Source code location in a git repository. (optional)
  #
  git:
    url: git2
    ref: {branch: main}

  # image with the app already built (optional)
  #
  image: registry/app-name/workload2     # (2)

  # resource constraints for the main application. (optional)
  #
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m
