apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: workload1-app
  labels:
    app.tanzu.vmware.com/workload-type: web

spec:
  git:
    url: git1
    ref: {branch: main}
    
  services:
    - apiVersion: services.tanzu.vmware.com/v1alpha1
      kind: backend-db

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: backend-db

resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m

---

apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: workload1-routes
  labels:
    app.tanzu.vmware.com/workload-type: simple

spec:
  git:
    url: git1/routes
    ref: {branch: main}
