apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: workload1-app
  labels:
    app.tanzu.vmware.com/workload-type: web

spec:
  git:
    url: git1
    ref: {branch: main}

resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m
---
apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: workload1-routes
  labels:
    app.tanzu.vmware.com/workload-type: simple

spec:
  git:
    url: git1/routes
    ref: {branch: main}
