apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: workload1
  labels:
    # label to be matched against a `ClusterSupplyChain`s label selector.
    #
    app.tanzu.vmware.com/workload-type: web   # (1)

spec:
  # Source code location in a git repository. (optional)
  #
  git:
    url: git1
    ref: {branch: main}


  # services to be bound through service-bindings (optional)
  #
  #services:
  #  - apiVersion: services.tanzu.vmware.com/v1alpha1
  #    kind: RabbitMQ


  # image with the app already built (optional)
  #
  image: registry/app-name/workload1     # (2)

  # (optional) environment variables to be passed to the main container
  # running the application.
  #
  #env:
  #  - name: SPRING_PROFILES_ACTIVE
  #    value: mysql


  # resource constraints for the main application. (optional)
  #
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m
