apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: vra-binder
spec:
  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:yaml", "yaml")
    
    !@ Binding to VRA managed PostgresSQL instance using VRA Service Broker
    !@
    !@ 1. VRA Service Broker configured
    !@ 2. PostgreSQLInstance instance mangaed by VRA
    !@
    apiVersion: api.mgmt.cloud.vmware.com/v1
    kind: ServiceBroker   
    metadata:
      name: dekt-vra-postgres
      labels:
        provider: dekt-provider-vra
        vpc: dekt-vpc-data-services
    spec: 
