# this is a mockup file to illustrate future AppStack concepts 
apiVersion: experimental.kontinue.io/v1
kind: Workload
metadata:
  name: {{appName}}-workflow
  labels:
    app.kubernetes.io/name: {{appName}}-workflow
    app.tanzu.vmware.com/workload-type: supplychain
  spec:
    components:
      - name: source-provider
        templateRef:
          kind: SourceTemplate
          name: git-repository-battery
      - name: build-image-provider
        templateRef:
          kind: BuildTemplate
          name: kpack-battery
        sources:
          - component: source-provider
            name: {{appName}}-builder
      - name: opinion-service-workload-template-provider
        templateRef:
          kind: OpinionTemplate
          name: {{appName}}-workflow
      -name: api-gateway-template
        templateRef:
          kind: OpinionTemplate
          name: web-micro-gateways
      
