#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.artifactId + "-api-portal"
spec:
  template:
    metadata:
      labels:
        app: #@ data.values.artifactId + "-api-portal"
    spec:
      containers:
      - name: #@ data.values.artifactId + "-api-portal"
        env:
          - name: API_PORTAL_SOURCE_URLS
            value: #@ data.values.openAPISources
