#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-portal-server
spec:
  template:
    metadata:
      labels:
        app: api-portal-server
    spec:
      containers:
      - name: api-portal-server
        env:
          - name: API_PORTAL_SOURCE_URLS
            value: scg-openapi.domain/openapi
#@ if data.values.portalScope == "brownfield":
             , #@ data.values.brownfieldSources
#@ end
---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata: 
  name: scg-openapi
  annotations: 
    kubernetes.io/ingress.class: nginx 
spec: 
  rules: 
    - host: scg-openapi.domain
      http: 
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: scg-operator
              port:
                number: 80
