#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: #@ data.values.artifactId + "-gateway"
spec:
  api:
    serverUrl: #@ "https://" + data.values.artifactId + "." + data.values.domain 
    title: #@ data.values.artifactId + "-micro-gateway"
    description: #@ "Micro Gateway to control internal APIs of " + data.values.artifactId
    version: 0.1.0
#@ if data.values.gwMetrics:
    scorecards: #@ data.values.apiScorecards 
#@ end
    cors:
      allowedOrigins:
        - #@ "api-portal." + data.values.domain
#@ if data.values.gwHA:  
  count: 3
#@ else:
  count: 1
#@ end
  sso:
    secret: #@ data.values.artifactId + "-" + data.values.ssoProvider + "-sso
#@ if data.values.gwMetrics:
  observability:
    metrics:
  #@ if data.values.wavefront:
      wavefront:
        enabled: true
        secret: #@ data.values.artifactId + "-observability"
        source: #@ data.values.artifactId + "-gateway"
        application: #@ data.values.artifactId
        service: #@ data.values.artifactId + "-gateway"
  #@ end
  #@ if data.values.prometheus:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          labels:
            release: #@ data.values.artifactId + "-prometheus"
  #@ end
#@ end
