#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: #@ data.values.workload1 + "-mapping"
spec:
  gatewayRef:
    name: #@ data.values.artifactID + "-gateway"
  routeConfigRef:
    name: #@ data.values.workload1 + "-routes"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: #@ data.values.workload1 + "-mapping"
spec:
  gatewayRef:
    name: #@ data.values.artifactID + "-gateway"
  routeConfigRef:
    name: #@ data.values.workload2 + "-routes"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: #@ data.values.workload3 + "-mapping"
spec:
  gatewayRef:
    name: #@ data.values.artifactID + "-gateway"
  routeConfigRef:
    name: #@ data.values.workload3 + "-routes"
