apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: {{microService1Name}}-mapping
spec:
  gatewayRef:
    name: {{appName}}-gateway
  routeConfigRef:
    name: {{microService1Name}}-routes
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: {{microService2Name}}-mapping
spec:
  gatewayRef:
    name: {{appName}}-gateway
  routeConfigRef:
    name: {{microService2Name}}-routes
