apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: workload1-mapping
spec:
  gatewayRef:
    name: app-name-gateway
  routeConfigRef:
    name: workload1-routes
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: workload2-mapping
spec:
  gatewayRef:
    name: app-name-gateway
  routeConfigRef:
    name: workload2-routes
