apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: subpath1-mapping
spec:
  gatewayRef:
    name: app-name-gateway
  routeConfigRef:
    name: subpath1-routes
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: subpath2-mapping
spec:
  gatewayRef:
    name: app-name-gateway
  routeConfigRef:
    name: subpath2-routes
