#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: #@ data.values.workloads[0] + "-mapping"
spec:
  gatewayRef:
    name: #@ data.values.artifactId + "-gateway"
  routeConfigRef:
    name: #@ data.values.workloads[0] + "-routes"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: #@ data.values.workloads[1] + "-mapping"
spec:
  gatewayRef:
    name: #@ data.values.artifactId + "-gateway"
  routeConfigRef:
    name: #@ data.values.workloads[1] + "-routes"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: #@ data.values.workloads[2] + "-mapping"
spec:
  gatewayRef:
    name: #@ data.values.artifactId + "-gateway"
  routeConfigRef:
    name: #@ data.values.workloads[2] + "-routes"
