#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: brownfield-routes-config
spec:
  service: 
    name: brownfield-proxy
  routes:
    - predicates:
        - Path=/api/browndfield-api/{adopterid}
        - Method=GET
      ssoEnabled: true
      filters:
        - RateLimit=3,60s
        - JwtKey={header:X-JWT-KEYID}
      title: "A brownfield API call for 3rd-party/legacy end point"
      tags:
        - Brownfield
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: brownfield-gateway
spec:
  count: 1
  api:
    serverUrl: http://browndield.apps.dekt.io
    title: User Verification Services
    description: External APIs to provide user verification services
    version: 0.5.0
    cors:
      allowedOrigins:
      - http://api-portal.apps.dekt.io
---
apiVersion: v1
kind: Service
metadata:
  name: datacheck-brownfield-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: datacheck-routes-mapping
spec:
  gatewayRef:
    name: datacheck-gateway
  routeConfigRef:
    name: datacheck-routes-config
