#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: $(workload.metadata.name)$-gateway
spec:
  api:
    serverUrl: https://$(workload.metadata.name)$-gateway.example.com
    title: $(workload.metadata.name)$ micro gateway
    description: Micro Gateway to control internal APIs of $(workload.metadata.name)$
    version: 0.1.0
    cors:
      allowedOrigins:
        - api-portal.example.com
#@ if "localdev" in data.values.gwSLA: 
  count: 1
#@ end
#@ if "teamdev" in data.values.gwSLA: 
  count: 2
#@ end
#@ if "integration" in data.values.gwSLA: 
  count: 3
#@ end
#@ if "production" in data.values.gwSLA: 
  count: 3
#@ end

  sso:
    secret: sso-secret
#@ if data.values.gwMetrics:
  observability:
    metrics:
      wavefront:
        enabled: true
    wavefront:
      secret: wavefront-secret
      source: $(workload.metadata.name)$-gateway
      application: $(workload.metadata.name)$
      service: $(workload.metadata.name)$-gateway
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          labels:
            release: $(workload.metadata.name)$-prometheus"
#@ end
