#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: $(workload.metadata.name)$-gateway"
spec:
  api:
    serverUrl: #@ "https://" + data.values.artifactId + "." + data.values.domain 
    title: #@ data.values.artifactId + "-micro-gateway"
    description: #@ "Micro Gateway to control internal APIs of " + data.values.artifactId
    version: 0.1.0
    cors:
      allowedOrigins:
        - api-portal.example.com
#@ if hasattr(data.values.gwSLA, "localdev")
  count: 1
#@ else:
  count: 3
#@ end
  sso:
    secret: sso-secret
#@ if data.values.gwMetrics:
  observability:
    metrics:
      wavefront:
        enabled: true
    wavefront:
      secret: wavefront-secret
      source: $(workload.metadata.name)$-gateway
      application: $(workload.metadata.name)$
      service: $(workload.metadata.name)$-gateway
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          labels:
            release: $(workload.metadata.name)$-prometheus"
#@ end
