#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: #@ data.values.artifactId + "-" + data.values.workloads[0] + "-routes"
spec:
  service: 
    name: #@ data.values.artifactId + "-" + data.values.workloads[0] + "-service"
#@ if data.values.portalScope == "public""
    ssoEnabled: true
#@ end 
  routes:
    - #@ "Route definitions imported at runtime from " + data.values.gitRepos[0] + "/routes"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: #@ data.values.artifactId + "-" + data.values.workloads[1] + "-routes"
spec:
  service: 
    name: #@ data.values.artifactId + "-" + data.values.workloads[1] + "-service"
#@ if data.values.portalScope == "public""
    ssoEnabled: true
#@ end 
  routes:
    - #@ "Route definitions imported at runtime from " + data.values.gitRepos[1] + "/routes"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: #@ data.values.artifactId + "-" + data.values.workloads[2] + "-routes"
spec:
  service: 
    name: #@ data.values.artifactId + "-" + data.values.workloads[2] + "-service"
#@ if data.values.portalScope == "public""
    ssoEnabled: true
#@ end 
  routes:
    - #@ "Route definitions imported at runtime from " + data.values.gitRepos[2] + "/routes"
