#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: #@ data.values.artifactId + "-" + data.values.workloads[0] + "-routes"
spec:
  service: 
    name: #@ data.values.artifactId + "-" + data.values.workloads[0] + "-service"
    predicates:
      - Header=X-Request-Id
#@ if data.values.forceSSO:
    ssoEnabled: true
#@ end 
#@ if data.values.forceRateLimit:
    filters:
      - RateLimit=2,60s
#@ end 
  routes: #@ "#Route definitions are imported from " + data.values.gitRepos[1]
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: #@ data.values.artifactId + "-" + data.values.workloads[1] + "-routes"
spec:
  service: 
    name: #@ data.values.artifactId + "-" + data.values.workloads[1] + "-service"
    predicates:
      - Header=X-Request-Id
#@ if data.values.forceSSO:
    ssoEnabled: true
#@ end 
#@ if data.values.forceRateLimit:
    filters:
      - RateLimit=2,60s
#@ end 
  routes:
    - #@ "Imported from " + data.values.gitRepos[1]
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: #@ data.values.artifactId + "-" + data.values.workloads[2] + "-routes"
spec:
  service: 
    name: #@ data.values.artifactId + "-" + data.values.workloads[2] + "-service"
    predicates:
      - Header=X-Request-Id
#@ if data.values.forceSSO:
    ssoEnabled: true
#@ end 
#@ if data.values.forceRateLimit:
    filters:
      - RateLimit=2,60s
#@ end 
  routes:
    - #@ "Imported from " + data.values.gitRepos[2]
