#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: $(workload.metadata.name)$-routes
spec:
  service: 
    name: $(workload.metadata.name)$-service
    predicates:
      - Header=X-Request-Id
#@ if "production" in data.values.gwSLA:
    ssoEnabled: true
#@ end 
#@ if "production" in data.values.gwSLA or "integration" in data.values.gwSLA:
    filters:
      - RateLimit=2,60s
#@ end 
  routes: $(sources.source-code.routes)$
