#
# WARNING: this yaml is for demonstration purposes only. Based on a work-in-progess product. Specs will change.
#
apiVersion: experimental.kontinue.io/v1
kind: Delivery
metadata:
  name: app-name-delivery
spec:
  selector:
    app.tanzu.vmware.com/workload-type: delivery

  #
  #   workload1-app => workload1-routes => gateway-mapping
  #     
  #     workload2-app => workload2-routes => gateway-mapping  
  #
  #         gateway-config
  #
  components:
    - name: app-name-delivery
      serviceAccountName: api-grid-deployer
      fetch:
        - inline:
            paths:
              - path: workload1-routes
                type: copy
                sources: $(workload1.git)$/api-routes.yaml
              - path: workload2-routes
                type: copy
                sources: $(workload2.git)$/api-routes.yaml
              - path: api-mapping
                type: copy
                sources: ../../apigrid/mapping.yaml
              - path: gateway-config
                type: copy
                sources: ../../apigrid/gateway.yaml
