#
# WARNING: this yaml is for demonstration purposes only. Based on a work-in-progess product. Specs will change.
#
apiVersion: carto.run/v1alpha1
kind: RunTemplate
metadata:
  name: app-name-pipeline
spec:
  completion:
    succeeded: {key: 'status.conditions.#(type=="Succeeded").status', value: "True"}
    failed:    {key: 'status.conditions.#(type=="Succeeded").status', value: "False"}

  template:
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: app-name-pipeline
    spec:
      pipelineRef: {name: api-grid}
      params:
        - name: workload1-source-url
          value: $(workload1.git)$
        - name: workload1-routes
          value: $(workload1.git)$/api-routes.yaml
        - name: workload2-source-url
          value: $(workload2.git)$
        - name: workload2-routes
          value: $(workload2.git)$/api-routes.yaml
        - name: api-mapping
          value: ../../apigrid/mapping.yaml
        - name: gateway-config
          value: ../../apigrid/gateway.yaml
