#
#  ---------------        ---------------       -------------------------
#  | Watch Repo  |  ==>   | Build Image | =>    | Deploy to Cluster     |
#  |  (Flux)     |        | (TBS)       |       | (CNR, k8s deployment) |
#  ---------------        ---------------       -------------------------
#
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: app-name-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: online-store-component
  components:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      sources:
        - component: source-provider
          name: source

    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app-deploy
      images:
        - component: image-builder
          name: image
