#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: #@ data.values.artifactId
spec:
  selector:
    app.tanzu.vmware.com/workload-type: online-store

  components:

    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source-code

#@ if data.values.scanScope == "src":
    - name: source-scanner
      templateRef:
        kind: ClusterSourceTemplate
        name: source
      sources:
      - component: source-provider
        name: source-code
#@ end
    
         
#@ if data.values.scanScope == "imgSrc":
    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: scanned-image
      images:
        - component: image-builder
          name: built-image
#@ end

#@ if data.values.addTesting:
    - name: pre-prod-tester
      templateRef:
        kind: ClusterSourceTemplate
        name: testing-pipeline
      sources:
        - component: source-scanner
          name: scanned-source
      
    - name: app-runner
      templateRef:
        kind: ClusterTemplate
        name: app-deploy
      images:
  #@ if data.values.scanScope == "srcImg":
        - component: image-scanner
          name: scanned-image
  #@ else:
        - component: image-builder
          name: image
#@ end         
