#
# Example of a simple Source to URL supply chain
#   
#  ---------------        ---------------       ------------------------       -------------------------
#  | Watch Repo  |  ==>   | Build Image | =>    | Apply Conventions    | ==>   | Deploy to Cluster     |
#  |  (Flux)     |        | (TBS)       |       | (Convention Service) |       | (CNR, k8s deployment) |
#  ---------------        ---------------       ------------------------       -------------------------
#
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: basic-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:

    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source-code

    - name: source-scanner
      templateRef:
        kind: ClusterSourceTemplate
        name: scanned-source
      sources:
      - component: source-provider
        name: source-code

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: built-image
      sources:
        - component: source-scanner
          name: scanned-source

    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: scanned-image
      images:
        - component: image-builder
          name: built-image
