#
# WARNING: this yaml is for demonstration purposes only. Based on a work-in-progess product. Specs will change.
#
apiVersion: kontinue.io/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: app-name-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:
  
    #provide source code for workload1 and workload2
    - name: workload1-source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: workload1-source-repo
    - name: workload2-source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: workload2-source-repo
        
    #test workload1 and workload2
    - name: workload1-tester
      templateRef:
        kind: ClusterSourceTemplate
        name: app-name-testing-pipeline
      sources:
        - component: workload1-source-provider
          name: workload1-tested-source
        - component: workload2-source-provider
          name: workload2-tested-source
    
    #build workload1 and workload2 images
    - name: image-builder-workload1
      templateRef:
        kind: ClusterBuildTemplate
        name: app-name-builder
      sources:
        - component: workload1-tester
          name: workload1-tested-source
      params:
        - name: java-version
          path: $(java-version)$

    - name: image-builder-workload2
      templateRef:
        kind: ClusterBuildTemplate
        name: app-name-builder
      sources:
        - component: workload2-tester
          name: workload2-tested-source
   
