#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: #@ data.values.artifactId
spec:
  selector:
    app.tanzu.vmware.com/workload-type: #@ data.values.workloadType
    #@ if data.values.addTesting:
    apps.tanzu.vmware.com/has-tests: 'true'
    #@ end

  resources:
  - name: SOURCE-PROVIDER
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  #@ if data.values.addTesting:
  - name: SOURCE-TESTER
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: testing-pipeline
  #@ end
  - name: SOURCE-SCANNER
    sources:
    - name: source
      resource: source-tester
    templateRef:
      kind: ClusterSourceTemplate
      name: source-scanner-template
  - name: IMAGE-BUILDER
    params:
    - name: serviceAccount
      value: default
    - name: clusterBuilder
      value: default
    sources:
    - name: source
      resource: source-scanner
    templateRef:
      kind: ClusterImageTemplate
      name: kpack-template
#@ if data.values.scanScope == "srcImg":   
  - name: IMAGE-SCANNER
    images:
    - name: image
      resource: image-builder
    templateRef:
      kind: ClusterImageTemplate
      name: image-scanner-template
  #@
  - name: CONFIG-PROVIDER
    images:
    - name: image
      resource: image-scanner
    name: config-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - name: APP-CONFIG
    configs:
    - name: config
      resource: config-provider
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      name: config-template
  - name: CONFIG-WRITER
    configs:
    - name: config
      resource: app-config
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template

      
#@ if "rdsPostgres" in data.values.serviceBinding:
    - name: 5-BIND-RDS-POSTGRESSQL
      templateRef:
        kind: ClusterTemplate
        name: rds-postgres-binder-template
      configs:
        - resource: 3-app-config
          name: app-config
#@ end    

#@ if "azureSQL" in data.values.serviceBinding:
    - name: 5-BIND-AZURE-SQL
      templateRef:
        kind: ClusterTemplate
        name: azure-sql-binder-template
      configs:
        - resource: 3-app-config
          name: app-config
#@ end

#@ if "gcpSQL" in data.values.serviceBinding:
    - name: 5-BIND-GCP-CLOUDSQL
      templateRef:
        kind: ClusterTemplate
        name: gcp-cloudql-service-binder-template
      configs:
        - resource: 3-app-config
          name: app-config
#@ end

#@ if "k8sRabbitMQ" in data.values.serviceBinding:
    - name: 5-BIND-K8S-RABBITMQ
      templateRef:
        kind: ClusterTemplate
        name: k8s-rabbitmq-binder-template
      configs:
        - resource: 3-app-config
          name: app-config
#@ end

#@ if "k8sPostgresSQL" in data.values.serviceBinding:
    - name: 5-BIND-K8S-POSTGRESSQL
      templateRef:
        kind: ClusterTemplate
        name: k8s-postgres-binder-template
      configs:
        - resource: 3-app-config
          name: app-config
#@ end   

#@ if "vmPostgresSQL" in data.values.serviceBinding:
    - name: 5-BIND-VM-POSTGRESSQL
      templateRef:
        kind: ClusterTemplate
        name: vm-postgres-binder-template
      configs:
        - resource: 3-app-config
          name: app-config
#@ end    

#@ if "core" in data.values.testScope:
    - name: 6-TEST-CORE
      templateRef:
        kind: PipelineTemplate
        name: core-testing-template
      configs:
        - resource: 3-app-config
          name: app-config
#@ end  

#@ if "data" in data.values.testScope:
    - name: 6-TEST-DATA
      templateRef:
        kind: PipelineTemplate
        name: data-testing-template
      configs:
        - resource: 3-app-config
          name: app-config
#@ end  

#@ if "api" in data.values.testScope:
    - name: 6-TEST-API
      templateRef:
        kind: PipelineTemplate
        name: api-testing-template
      configs:
        - resource: 3-app-config
          name: app-config
#@ end

  params:
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: ''
    name: gitops_ssh_secret
