#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: #@ data.values.artifactId
spec:
  selector:
    app.tanzu.vmware.com/workload-type: #@ data.values.workloadType

  resources:
    - name: 1-APP-SOURCE
      templateRef:
        kind: ClusterSourceTemplate
        name: source-template

    - name: 2-APP-SOURCE-SCAN
      templateRef:
        kind: ClusterSourceTemplate
        name: source-scanning-template
      sources:
        - resource: 1-APP-SOURCE 
          name: source
          
    
    - name: 3-APP-IMAGE
      templateRef:
        kind: ClusterImageTemplate
        name: image-builder-template
      sources:
        - resource: 2-APP-SOURCE-SCAN
          name: scanned-source
          
          
#@ if data.values.scanScope == "srcImg":    
    - name: 4-APP-IMAGE-SCAN
      templateRef:
        kind: ClusterImageTemplate
        name: image-scanning-template
      images:
        - component: 3-APP-IMAGE
          name: image
          
          
#@ end

    - name: 5-APP-CONFIG
      templateRef:
        kind: ClusterConfigTemplate
        name: convention-template
      images:
      #@ if data.values.scanScope == "srcImg":
        - component: 4-APP-IMAGE-SCAN
          name: scanned-image
      #@ else:
        - component: 3-APP-IMAGE
          name: image
      #@ end     
    
    - name: 6-APP-DEPLOY
      templateRef:
        kind: ClusterTemplate
        name: app-deploy-cnr-template
      configs:
        - resource: 5-APP-CONFIG
          name: app-config
          
      
#@ if data.values.addClusterDataServices:
    - name: 7-BIND-CLUSTER-SERVICE
      templateRef:
        kind: ClusterTemplate
        name: cluster-service-binder-template
      configs:
        - resource: 5-APP-CONFIG
          name: app-config
#@ end    

#@ if data.values.addCloudDataServices:
    - name: 7-BIND-CLOUD-SERVICE
      templateRef:
        kind: ClusterTemplate
        name: cloud-service-binder-template
      configs:
        - resource: 5-APP-CONFIG
          name: app-config
#@ end

#@ if data.values.addTesting:
    - name: 8-TEST-INTEGRATIONS
      templateRef:
        kind: PipelineTemplate
        name: integration-testing-template
      sources:
    #@ if len(data.values.testScope) > 0:
        - resource: testing-scopes
          value: #@ data.values.testScope
    #@ else:
        - resource: testing-scopes
          value: core
    #@ end
#@ end  
