apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: app-name-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  #
  #
  #  source-provider  -->  [src]  -->  image-builder  -->  [img]  ---> api-config  --->  [apis]  -->  deployer
  #    git workload1                     image workload1                 apis workload1                 app-name
  #    git workload2                     image workload2                 apis workload2
  #
  components:
  
    # git repos are used to provide source code
    - name: app-name-source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: git-repository-battery
        
    # Tanzu Build Service is used to build source to image 
    - name: app-name-image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: pack-battery

    # define all the workloads that construct this business application
      sources:
        - component: app-name-source-provider
          name: workload1
        - component: app-name-source-provider
          name: workload2

    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app-deploy
      images:
        - component: image-builder
          name: image


      params:
        - name: java-version
          path: $(java-version)$

    - name: image-builder-workload2
      templateRef:
        kind: ClusterBuildTemplate
        name: app-name-builder
      sources:
        - component: workload2-tester
          name: workload2-tested-source
   
