#@ load("@ytt:data", "data")
---
# #@ data.values.artifactId Supply Chain workflow description:
#   
#   * Watch Repo (Flux)
#   * Build Image (TBS) =>
#@ if data.values.addConvenstions:
#   * Apply Conventions (Convention Service)
#@ end
#@ if data.values.scanScope == "src":
#   * Source scanning (ClusterSourceTemplate)
#@ end
#@ if data.values.scanScope == "img":
#   * Image scanning (ClusterImageTemplate)
#@ end
#@ if data.values.addTesting:
#   * Pre-prod testing (Tekton pipeline)
#@ end
#   * Deploy to Cluster (CNR, k8s deployment)
#
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:

    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source-code
#@ if data.values.addConvenstions:
  
#@ end
    - name: source-scanner
      templateRef:
        kind: ClusterSourceTemplate
        name: scanned-source
      sources:
      - component: source-provider
        name: source-code

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: built-image
      sources:
        - component: source-scanner
          name: scanned-source

    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: scanned-image
      images:
        - component: image-builder
          name: built-image
