apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: app-name-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  #  app-name deployment workflow:
  #
  #  source-provider --> [src] --> image-builder --> [img] --> deployer
  #    git workload1                 image workload1             app-name 
  #    git workload2                 image workload2             apis workload1
  #                                                              apis workload2
  #                                                              app-name-mapping
  #                                                              app-name-gateway
  #
  components:
  
    # git repos are used to provide source code
    - name: workload1-source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: workload1-source
    - name: workload2-source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: workload2-source
        
    # Tanzu Build Service is used to build source to image 
    - name: workload1-image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: workload1-image
    - name: workload2-image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: workload1-image

    # define all the workloads that construct this business application
      sources:
        - component: app-name-source-provider
          name: workload1
        - component: app-name-source-provider
          name: workload2

    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app-deploy
      images:
        - component: image-builder
          name: image

   
