#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: #@ data.values.artifactId
spec:
  selector:
    app.tanzu.vmware.com/workload-type: #@ data.values.workloadType

  resources:
    
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: app-source

    - name: source-scanner
      templateRef:
        kind: ClusterSourceTemplate
        name: app-source-scanned
      sources:
      - component: source-provider
        name: app-source
    
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: app-image
      sources:
        - resource: source-provider
          name: app-source-scanned

#@ if data.values.scanScope == "srcImg":    
    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: app-image-scanned
      images:
        - component: image-builder
          name: app-image
#@ end

#@ if data.values.addCNR:
    - name: app-runner
      templateRef:
        kind: ClusterTemplate
        name: app-deployed
      images:
  #@ if data.values.scanScope == "srcImg":
        - component: image-scanner
          name: app-image-scanned
  #@ else:
        - component: image-builder
          name: app-image
  #@ end
#@ end

#@ if data.values.addDataServicesBinding:
    #@ if data.values.serviceClaimsScope.contains("clusterOperators"):
    - name: cluster-service-binding
      templateRef:
        kind: ClusterBindTemplate
        name: app-bind-cluster
      sources:
        - resource: app-runner
          name: app-deployed
    #@ end
    #@ if data.values.serviceClaimsScope == "awsBroker":
    - name: aws-service-binding
      templateRef:
        kind: AWSBindTemplate
        name: app-bind-aws
      sources:
        - resource: app-runner
          name: app-deployed
    #@ end
    #@ if data.values.serviceClaimsScope == "azureBroker":
    - name: azure-service-binding
      templateRef:
        kind: AzureBindTemplate
        name: app-bind-azure
      sources:
        - resource: app-runner
          name: app-deployed
    #@ end
    #@ if data.values.serviceClaimsScope == "googleBroker":
    - name: google-service-binding
      templateRef:
        kind: GCPBindTemplate
        name: app-bind-google
      sources:
        - resource: app-runner
          name: app-deployed
    #@ end
    #@ if data.values.serviceClaimsScope == "tanzuCatalog":
    - name: tanzucatalog-service-binding
      templateRef:
        kind: TanzuCatalogBindTemplate
        name: app-bind-tanzu-catalog
      sources:
        - resource: app-runner
          name: app-deployed
    #@ end
#@ end

#@ if data.values.addTesting:
    - name: pre-prod-tester
      templateRef:
        kind: PipelineTemplate
        name: run-pre-prod-testing
      sources:
    #@ if len(data.values.testScope) > 0:
        - resource: testing-scopes
          value: #@ data.values.testScope
    #@ else:
        - resource: testing-scopes
          value: core
    #@ end
#@ end  
