#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: #@ data.values.artifactId
spec:
  selector:
    app.tanzu.vmware.com/workload-type: online-store

  resources:
    
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: app-source

    - name: source-scanner
      templateRef:
        kind: ClusterSourceTemplate
        name: app-source-scanned
      sources:
      - component: source-provider
        name: app-source
    
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: app-image
      sources:
        - resource: source-provider
          name: app-source-scanned

#@ if data.values.scanScope == "srcImg":    
    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: app-image-scanned
      images:
        - component: image-builder
          name: app-image
#@ end
   
    - name: app-runner
      templateRef:
        kind: ClusterTemplate
        name: app-deployed
      images:
  #@ if data.values.scanScope == "srcImg":
        - component: image-scanner
          name: app-image-scanned
  #@ else:
        - component: image-builder
          name: app-image
  #@ end

#@ if data.values.addExternalServices:
    
    - name: external-service-binding
      templateRef:
        kind: BindTemplate
        name: app-deployed-bind
      sources:
        - resource: app-runner
          name: app-deployed
#@ end

#@ if data.values.addTesting:
    - name: pre-prod-tester
      templateRef:
        kind: PipelineTemplate
        name: run-pre-prod-testing
      sources:
    #@ if len(data.values.testScope) > 0:
        - resource: testing-scopes
          value: #@ data.values.testScope
    #@ else:
        - resource: testing-scopes
          value: core
    #@ end
#@ end  
