#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: #@ data.values.artifactId
spec:
  selector:
    app.tanzu.vmware.com/workload-type: #@ data.values.workloadType

  resources:
   # test comment
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source-template

    - name: source-scanner
      templateRef:
        kind: ClusterSourceTemplate
        name: source-scanning-template
      sources:
        - name: source
          resource: source-provider
    
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image-builder-template
      sources:
        - name: scanned-source
          resource: source-scanner
          
#@ if data.values.scanScope == "srcImg":    
    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: image-scanning-template
      images:
        - name: image
          component: image-builder
          
#@ end

    - name: config-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: convention-template
      images:
      #@ if data.values.scanScope == "srcImg":
        - name: scanned-image
          component: image-scanner
      #@ else:
        - name: image
          component: image-builder
      #@ end     
    
    - name: app-deployer
      templateRef:
        kind: ClusterTemplate
        name: app-deploy-cnr-template
      configs:
        - name: app-config
          resource: config-provider
      
#@ if data.values.addClusterDataServices:
    - name: cluster-service-binder
      templateRef:
        kind: ClusterTemplate
        name: cluster-service-binder-template
      configs:
        - name: app-config
          resource: config-provider
#@ end    

#@ if data.values.addCloudDataServices:
    - name: cloud-service-binder
      templateRef:
        kind: ClusterTemplate
        name: cloud-service-binder-template
      configs:
        - name: app-config
          resource: config-provider
#@ end

#@ if data.values.addTesting:
    - name: integration-testing-provider
      templateRef:
        kind: PipelineTemplate
        name: integration-testing-template
      sources:
    #@ if len(data.values.testScope) > 0:
        - resource: testing-scopes
          value: #@ data.values.testScope
    #@ else:
        - resource: testing-scopes
          value: core
    #@ end
#@ end  
