apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  #
  #
  #   |-> source-provider --> [workload-git]  
  #       |-> source-tester --> [workload-source]
  #           |-> image-builder --> [workload-image]
  #               |-> image-deployer --> [workload-app]
  #
  #
  components:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: workload-source
        
    - name: source-tester
      templateRef:
        kind: ClusterSourceTemplate
        name: workload-pipeline
      sources:
        - component: source-provider
          name: workload-source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: workload-image
      sources:
        - component: source-provider
          name: source
          
    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: workload-deploy
      images:
        - component: image-builder
          name: workload-image
