#@ load("@ytt:data", "data")
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.workloads[0]
  labels:
    app.tanzu.vmware.com/workload-type: online-store

spec:
  source:
    git:
      url: #@ data.values.gitRepos[0]
      ref:
        branch: "main"
        tag: "v1.0.0"
  services:
    - apiVersion: services.tanzu.vmware.com/v1alpha1
      kind: prod-db
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod

  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m

  params:
    - name: java-version
      value: 11
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.workloads[1]
  labels:
    app.tanzu.vmware.com/workload-type: online-store

spec:
  source:
    git:
      url: #@ data.values.gitRepos[1]
      ref:
        branch: "main"
        tag: "v1.0.0"

  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.workloads[2]
  labels:
    app.kubernetes.io/name: workload3
    app.tanzu.vmware.com/workload-type: online-store
spec:
  source:
    git:
      url: #@ data.values.gitRepos[2]
      ref:
        branch: main
