apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload1
  labels:
    app.tanzu.vmware.com/workload-type: online-store-component

spec:
  source:
    git:
      url: git-repo1
      ref:
        branch: "main"
        tag: "v1.0.0"
        
  services:
    - apiVersion: services.tanzu.vmware.com/v1alpha1
      kind: store-db

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod

  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m

  params:
    - name: java-version
      value: 11
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload2
  labels:
    app.tanzu.vmware.com/workload-type: online-store-component

spec:
  source:
    git:
      url: git-repo2
      ref:
        branch: "main"
        tag: "v1.0.0"

  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload3
  labels:
    app.kubernetes.io/name: workload3
    app.tanzu.vmware.com/workload-type: online-store-component
spec:
  source:
    git:
      url: git-repo3
      ref:
        branch: main
