apiVersion: kontinue.io/v1alpha1
kind: ConfigTemplate
metadata:
  name: cluster-sink-battery
spec:
  # default paramters. see ClusterSourceTemplate for more info. (optional)
  #
  params: []

  # how to template out the kubernetes object. (required)
  #
  template:
    apiVersion: kontinue.io/v1alpha1
    kind: Deliverable
    metadata:
      name: $(workload.name)$
      labels:
        app.tanzu.vmware.com/workload-type: web
    value: $(opinions[0].opinion)$
